# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f8c446d88af9f13ac49947a87c47207"
name = "safety-gate-monitor-eu"
application_url = "https://harbor-celebrate-postage-asin.trycloudflare.com"
embedded = true
handle = "safety-gate-monitor-eu"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://harbor-celebrate-postage-asin.trycloudflare.com/auth/callback", "https://harbor-celebrate-postage-asin.trycloudflare.com/auth/shopify/callback", "https://harbor-celebrate-postage-asin.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
